# Generated by Django 4.1.3 on 2022-11-08 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeworkarrangement",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
