# Generated by Django 4.1.3 on 2022-11-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_alter_employeeworkarrangement_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workarrangement",
            name="work",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name="workarrangement",
            unique_together={("work", "work_type")},
        ),
    ]
